window.esdocSearchIndex = [
  [
    "requex/src/constants.js~all_event_types",
    "variable/index.html#static-variable-ALL_EVENT_TYPES",
    "<span>ALL_EVENT_TYPES</span> <span class=\"search-result-import-path\">requex/src/constants.js</span>",
    "variable"
  ],
  [
    "requex/src/index.js~constants",
    "variable/index.html#static-variable-Constants",
    "<span>Constants</span> <span class=\"search-result-import-path\">requex/src/index.js</span>",
    "variable"
  ],
  [
    "requex/src/events.js~events",
    "class/src/events.js~Events.html",
    "<span>Events</span> <span class=\"search-result-import-path\">requex/src/events.js</span>",
    "class"
  ],
  [
    "requex/src/index.js~from",
    "class/src/index.js~From.html",
    "<span>From</span> <span class=\"search-result-import-path\">requex/src/index.js</span>",
    "class"
  ],
  [
    "requex/src/reducer-builder.js~reducerbuilder",
    "class/src/reducer-builder.js~ReducerBuilder.html",
    "<span>ReducerBuilder</span> <span class=\"search-result-import-path\">requex/src/reducer-builder.js</span>",
    "class"
  ],
  [
    "requex/src/reducer-descriptor.js~reducerdescriptor",
    "class/src/reducer-descriptor.js~ReducerDescriptor.html",
    "<span>ReducerDescriptor</span> <span class=\"search-result-import-path\">requex/src/reducer-descriptor.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/constants.js",
    "file/src/constants.js.html",
    "src/constants.js",
    "file"
  ],
  [
    "src/events.js",
    "file/src/events.js.html",
    "src/events.js",
    "file"
  ],
  [
    "src/events.js~events#ofanytype",
    "class/src/events.js~Events.html#instance-method-ofAnyType",
    "src/events.js~Events#ofAnyType",
    "method"
  ],
  [
    "src/events.js~events#oftype",
    "class/src/events.js~Events.html#instance-method-ofType",
    "src/events.js~Events#ofType",
    "method"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/index.js~from.events",
    "class/src/index.js~From.html#static-method-events",
    "src/index.js~From.events",
    "method"
  ],
  [
    "src/index.js~from.structure",
    "class/src/index.js~From.html#static-method-structure",
    "src/index.js~From.structure",
    "method"
  ],
  [
    "src/index.js~from.value",
    "class/src/index.js~From.html#static-method-value",
    "src/index.js~From.value",
    "method"
  ],
  [
    "src/reducer-builder.js",
    "file/src/reducer-builder.js.html",
    "src/reducer-builder.js",
    "file"
  ],
  [
    "src/reducer-builder.js~reducerbuilder#build",
    "class/src/reducer-builder.js~ReducerBuilder.html#instance-method-build",
    "src/reducer-builder.js~ReducerBuilder#build",
    "method"
  ],
  [
    "src/reducer-builder.js~reducerbuilder#handledeventtypes",
    "class/src/reducer-builder.js~ReducerBuilder.html#instance-member-handledEventTypes",
    "src/reducer-builder.js~ReducerBuilder#handledEventTypes",
    "member"
  ],
  [
    "src/reducer-builder.js~reducerbuilder#reducechain",
    "class/src/reducer-builder.js~ReducerBuilder.html#instance-member-reduceChain",
    "src/reducer-builder.js~ReducerBuilder#reduceChain",
    "member"
  ],
  [
    "src/reducer-builder.js~reducerbuilder#select",
    "class/src/reducer-builder.js~ReducerBuilder.html#instance-method-select",
    "src/reducer-builder.js~ReducerBuilder#select",
    "method"
  ],
  [
    "src/reducer-builder.js~reducerbuilder#sum",
    "class/src/reducer-builder.js~ReducerBuilder.html#instance-method-sum",
    "src/reducer-builder.js~ReducerBuilder#sum",
    "method"
  ],
  [
    "src/reducer-builder.js~reducerbuilder#where",
    "class/src/reducer-builder.js~ReducerBuilder.html#instance-method-where",
    "src/reducer-builder.js~ReducerBuilder#where",
    "method"
  ],
  [
    "src/reducer-descriptor.js",
    "file/src/reducer-descriptor.js.html",
    "src/reducer-descriptor.js",
    "file"
  ],
  [
    "src/reducer-descriptor.js~reducerdescriptor#constructor",
    "class/src/reducer-descriptor.js~ReducerDescriptor.html#instance-constructor-constructor",
    "src/reducer-descriptor.js~ReducerDescriptor#constructor",
    "method"
  ],
  [
    "src/reducer-descriptor.js~reducerdescriptor#handledeventtypes",
    "class/src/reducer-descriptor.js~ReducerDescriptor.html#instance-member-handledEventTypes",
    "src/reducer-descriptor.js~ReducerDescriptor#handledEventTypes",
    "member"
  ],
  [
    "src/reducer-descriptor.js~reducerdescriptor#reduce",
    "class/src/reducer-descriptor.js~ReducerDescriptor.html#instance-member-reduce",
    "src/reducer-descriptor.js~ReducerDescriptor#reduce",
    "member"
  ]
]