window.esdocSearchIndex = [
  [
    "requex/src/reducers/storage-keys.js~addition_source",
    "variable/index.html#static-variable-ADDITION_SOURCE",
    "<span>ADDITION_SOURCE</span> <span class=\"search-result-import-path\">requex/src/reducers/storage-keys.js</span>",
    "variable"
  ],
  [
    "requex/src/reducers/storage-keys.js~args_prefix",
    "variable/index.html#static-variable-ARGS_PREFIX",
    "<span>ARGS_PREFIX</span> <span class=\"search-result-import-path\">requex/src/reducers/storage-keys.js</span>",
    "variable"
  ],
  [
    "requex/src/reducers/any-event-reducer.js~anyeventreducer",
    "class/src/reducers/any-event-reducer.js~AnyEventReducer.html",
    "<span>AnyEventReducer</span> <span class=\"search-result-import-path\">requex/src/reducers/any-event-reducer.js</span>",
    "class"
  ],
  [
    "requex/src/reducers/collection-reducer.js~collectionreducer",
    "class/src/reducers/collection-reducer.js~CollectionReducer.html",
    "<span>CollectionReducer</span> <span class=\"search-result-import-path\">requex/src/reducers/collection-reducer.js</span>",
    "class"
  ],
  [
    "requex/src/reducers/dictionary-object-reducer.js~dictionaryobjectreducer",
    "class/src/reducers/dictionary-object-reducer.js~DictionaryObjectReducer.html",
    "<span>DictionaryObjectReducer</span> <span class=\"search-result-import-path\">requex/src/reducers/dictionary-object-reducer.js</span>",
    "class"
  ],
  [
    "requex/src/reducers/event-reducer.js~eventreducer",
    "class/src/reducers/event-reducer.js~EventReducer.html",
    "<span>EventReducer</span> <span class=\"search-result-import-path\">requex/src/reducers/event-reducer.js</span>",
    "class"
  ],
  [
    "requex/src/reducers/filtered-reducer.js~filteredreducer",
    "class/src/reducers/filtered-reducer.js~FilteredReducer.html",
    "<span>FilteredReducer</span> <span class=\"search-result-import-path\">requex/src/reducers/filtered-reducer.js</span>",
    "class"
  ],
  [
    "requex/src/reducers/flat-reduced-reducer.js~flatreducedreducer",
    "class/src/reducers/flat-reduced-reducer.js~FlatReducedReducer.html",
    "<span>FlatReducedReducer</span> <span class=\"search-result-import-path\">requex/src/reducers/flat-reduced-reducer.js</span>",
    "class"
  ],
  [
    "requex/src/reducers/folding-reducer.js~foldingreducer",
    "class/src/reducers/folding-reducer.js~FoldingReducer.html",
    "<span>FoldingReducer</span> <span class=\"search-result-import-path\">requex/src/reducers/folding-reducer.js</span>",
    "class"
  ],
  [
    "requex/src/reducers/storage-keys.js~inner_source",
    "variable/index.html#static-variable-INNER_SOURCE",
    "<span>INNER_SOURCE</span> <span class=\"search-result-import-path\">requex/src/reducers/storage-keys.js</span>",
    "variable"
  ],
  [
    "requex/src/index.js~linkedlist",
    "variable/index.html#static-variable-LinkedList",
    "<span>LinkedList</span> <span class=\"search-result-import-path\">requex/src/index.js</span>",
    "variable"
  ],
  [
    "requex/src/linked-list.js~linkedlist",
    "class/src/linked-list.js~LinkedList.html",
    "<span>LinkedList</span> <span class=\"search-result-import-path\">requex/src/linked-list.js</span>",
    "class"
  ],
  [
    "requex/src/reducers/linked-list-reducer.js~linkedlistreducer",
    "class/src/reducers/linked-list-reducer.js~LinkedListReducer.html",
    "<span>LinkedListReducer</span> <span class=\"search-result-import-path\">requex/src/reducers/linked-list-reducer.js</span>",
    "class"
  ],
  [
    "requex/src/reducers/mapped-reducer.js~mappedreducer",
    "class/src/reducers/mapped-reducer.js~MappedReducer.html",
    "<span>MappedReducer</span> <span class=\"search-result-import-path\">requex/src/reducers/mapped-reducer.js</span>",
    "class"
  ],
  [
    "requex/src/reducers/never-reducer.js~neverreducer",
    "class/src/reducers/never-reducer.js~NeverReducer.html",
    "<span>NeverReducer</span> <span class=\"search-result-import-path\">requex/src/reducers/never-reducer.js</span>",
    "class"
  ],
  [
    "requex/src/index.js~option",
    "variable/index.html#static-variable-Option",
    "<span>Option</span> <span class=\"search-result-import-path\">requex/src/index.js</span>",
    "variable"
  ],
  [
    "requex/src/option.js~option",
    "class/src/option.js~Option.html",
    "<span>Option</span> <span class=\"search-result-import-path\">requex/src/option.js</span>",
    "class"
  ],
  [
    "requex/src/reducers/storage-keys.js~removal_source",
    "variable/index.html#static-variable-REMOVAL_SOURCE",
    "<span>REMOVAL_SOURCE</span> <span class=\"search-result-import-path\">requex/src/reducers/storage-keys.js</span>",
    "variable"
  ],
  [
    "requex/src/reducers/storage-keys.js~root",
    "variable/index.html#static-variable-ROOT",
    "<span>ROOT</span> <span class=\"search-result-import-path\">requex/src/reducers/storage-keys.js</span>",
    "variable"
  ],
  [
    "requex/src/index.js~reduce",
    "class/src/index.js~Reduce.html",
    "<span>Reduce</span> <span class=\"search-result-import-path\">requex/src/index.js</span>",
    "class"
  ],
  [
    "requex/src/reducers/reducer.js~reducer",
    "class/src/reducers/reducer.js~Reducer.html",
    "<span>Reducer</span> <span class=\"search-result-import-path\">requex/src/reducers/reducer.js</span>",
    "class"
  ],
  [
    "requex/src/reducer-builder.js~reducerbuilder",
    "class/src/reducer-builder.js~ReducerBuilder.html",
    "<span>ReducerBuilder</span> <span class=\"search-result-import-path\">requex/src/reducer-builder.js</span>",
    "class"
  ],
  [
    "requex/src/reducer-context.js~reducercontext",
    "class/src/reducer-context.js~ReducerContext.html",
    "<span>ReducerContext</span> <span class=\"search-result-import-path\">requex/src/reducer-context.js</span>",
    "class"
  ],
  [
    "requex/src/reducer-query.js~reducerquery",
    "class/src/reducer-query.js~ReducerQuery.html",
    "<span>ReducerQuery</span> <span class=\"search-result-import-path\">requex/src/reducer-query.js</span>",
    "class"
  ],
  [
    "requex/src/reducers/storage-keys.js~source",
    "variable/index.html#static-variable-SOURCE",
    "<span>SOURCE</span> <span class=\"search-result-import-path\">requex/src/reducers/storage-keys.js</span>",
    "variable"
  ],
  [
    "requex/src/reducers/scoped-reducer.js~scopedreducer",
    "class/src/reducers/scoped-reducer.js~ScopedReducer.html",
    "<span>ScopedReducer</span> <span class=\"search-result-import-path\">requex/src/reducers/scoped-reducer.js</span>",
    "class"
  ],
  [
    "requex/src/reducers/structure-reducer.js~structurereducer",
    "class/src/reducers/structure-reducer.js~StructureReducer.html",
    "<span>StructureReducer</span> <span class=\"search-result-import-path\">requex/src/reducers/structure-reducer.js</span>",
    "class"
  ],
  [
    "requex/src/reducers/storage-keys.js~value",
    "variable/index.html#static-variable-VALUE",
    "<span>VALUE</span> <span class=\"search-result-import-path\">requex/src/reducers/storage-keys.js</span>",
    "variable"
  ],
  [
    "requex/src/reducers/value-reducer.js~valuereducer",
    "class/src/reducers/value-reducer.js~ValueReducer.html",
    "<span>ValueReducer</span> <span class=\"search-result-import-path\">requex/src/reducers/value-reducer.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/index.js~reduce.collectionconfiguration",
    "typedef/index.html#static-typedef-CollectionConfiguration",
    "src/index.js~Reduce.CollectionConfiguration",
    "typedef"
  ],
  [
    "src/index.js~reduce.allevents",
    "class/src/index.js~Reduce.html#static-method-allEvents",
    "src/index.js~Reduce.allEvents",
    "method"
  ],
  [
    "src/index.js~reduce.dictionaryobjectof",
    "class/src/index.js~Reduce.html#static-method-dictionaryObjectOf",
    "src/index.js~Reduce.dictionaryObjectOf",
    "method"
  ],
  [
    "src/index.js~reduce.eventsoftype",
    "class/src/index.js~Reduce.html#static-method-eventsOfType",
    "src/index.js~Reduce.eventsOfType",
    "method"
  ],
  [
    "src/index.js~reduce.linkedlistof",
    "class/src/index.js~Reduce.html#static-method-linkedListOf",
    "src/index.js~Reduce.linkedListOf",
    "method"
  ],
  [
    "src/index.js~reduce.never",
    "class/src/index.js~Reduce.html#static-method-never",
    "src/index.js~Reduce.never",
    "method"
  ],
  [
    "src/index.js~reduce.structure",
    "class/src/index.js~Reduce.html#static-method-structure",
    "src/index.js~Reduce.structure",
    "method"
  ],
  [
    "src/index.js~reduce.value",
    "class/src/index.js~Reduce.html#static-method-value",
    "src/index.js~Reduce.value",
    "method"
  ],
  [
    "src/linked-list.js",
    "file/src/linked-list.js.html",
    "src/linked-list.js",
    "file"
  ],
  [
    "src/linked-list.js~linkedlist.cons",
    "class/src/linked-list.js~LinkedList.html#static-method-cons",
    "src/linked-list.js~LinkedList.cons",
    "method"
  ],
  [
    "src/linked-list.js~linkedlist.filter",
    "class/src/linked-list.js~LinkedList.html#static-method-filter",
    "src/linked-list.js~LinkedList.filter",
    "method"
  ],
  [
    "src/linked-list.js~linkedlist.foreach",
    "class/src/linked-list.js~LinkedList.html#static-method-forEach",
    "src/linked-list.js~LinkedList.forEach",
    "method"
  ],
  [
    "src/linked-list.js~linkedlist.isempty",
    "class/src/linked-list.js~LinkedList.html#static-method-isEmpty",
    "src/linked-list.js~LinkedList.isEmpty",
    "method"
  ],
  [
    "src/linked-list.js~linkedlist.map",
    "class/src/linked-list.js~LinkedList.html#static-method-map",
    "src/linked-list.js~LinkedList.map",
    "method"
  ],
  [
    "src/linked-list.js~linkedlist.nil",
    "class/src/linked-list.js~LinkedList.html#static-method-nil",
    "src/linked-list.js~LinkedList.nil",
    "method"
  ],
  [
    "src/linked-list.js~linkedlist.ofarray",
    "class/src/linked-list.js~LinkedList.html#static-method-ofArray",
    "src/linked-list.js~LinkedList.ofArray",
    "method"
  ],
  [
    "src/linked-list.js~linkedlist.reduce",
    "class/src/linked-list.js~LinkedList.html#static-method-reduce",
    "src/linked-list.js~LinkedList.reduce",
    "method"
  ],
  [
    "src/linked-list.js~linkedlist.reverse",
    "class/src/linked-list.js~LinkedList.html#static-method-reverse",
    "src/linked-list.js~LinkedList.reverse",
    "method"
  ],
  [
    "src/linked-list.js~linkedlist.toarray",
    "class/src/linked-list.js~LinkedList.html#static-method-toArray",
    "src/linked-list.js~LinkedList.toArray",
    "method"
  ],
  [
    "src/option.js",
    "file/src/option.js.html",
    "src/option.js",
    "file"
  ],
  [
    "src/option.js~option#bind",
    "class/src/option.js~Option.html#instance-method-bind",
    "src/option.js~Option#bind",
    "method"
  ],
  [
    "src/option.js~option#filter",
    "class/src/option.js~Option.html#instance-method-filter",
    "src/option.js~Option#filter",
    "method"
  ],
  [
    "src/option.js~option#get",
    "class/src/option.js~Option.html#instance-method-get",
    "src/option.js~Option#get",
    "method"
  ],
  [
    "src/option.js~option#isnone",
    "class/src/option.js~Option.html#instance-member-isNone",
    "src/option.js~Option#isNone",
    "member"
  ],
  [
    "src/option.js~option#issome",
    "class/src/option.js~Option.html#instance-member-isSome",
    "src/option.js~Option#isSome",
    "member"
  ],
  [
    "src/option.js~option#map",
    "class/src/option.js~Option.html#instance-method-map",
    "src/option.js~Option#map",
    "method"
  ],
  [
    "src/option.js~option#otherwise",
    "class/src/option.js~Option.html#instance-method-otherwise",
    "src/option.js~Option#otherwise",
    "method"
  ],
  [
    "src/option.js~option#reduce",
    "class/src/option.js~Option.html#instance-method-reduce",
    "src/option.js~Option#reduce",
    "method"
  ],
  [
    "src/option.js~option.none",
    "class/src/option.js~Option.html#static-method-none",
    "src/option.js~Option.none",
    "method"
  ],
  [
    "src/option.js~option.some",
    "class/src/option.js~Option.html#static-method-some",
    "src/option.js~Option.some",
    "method"
  ],
  [
    "src/reducer-builder.js",
    "file/src/reducer-builder.js.html",
    "src/reducer-builder.js",
    "file"
  ],
  [
    "src/reducer-builder.js~reducerbuilder#build",
    "class/src/reducer-builder.js~ReducerBuilder.html#instance-method-build",
    "src/reducer-builder.js~ReducerBuilder#build",
    "method"
  ],
  [
    "src/reducer-builder.js~reducerbuilder#filter",
    "class/src/reducer-builder.js~ReducerBuilder.html#instance-method-filter",
    "src/reducer-builder.js~ReducerBuilder#filter",
    "method"
  ],
  [
    "src/reducer-builder.js~reducerbuilder#flatreduce",
    "class/src/reducer-builder.js~ReducerBuilder.html#instance-method-flatReduce",
    "src/reducer-builder.js~ReducerBuilder#flatReduce",
    "method"
  ],
  [
    "src/reducer-builder.js~reducerbuilder#fold",
    "class/src/reducer-builder.js~ReducerBuilder.html#instance-method-fold",
    "src/reducer-builder.js~ReducerBuilder#fold",
    "method"
  ],
  [
    "src/reducer-builder.js~reducerbuilder#map",
    "class/src/reducer-builder.js~ReducerBuilder.html#instance-method-map",
    "src/reducer-builder.js~ReducerBuilder#map",
    "method"
  ],
  [
    "src/reducer-builder.js~reducerbuilder#scoped",
    "class/src/reducer-builder.js~ReducerBuilder.html#instance-method-scoped",
    "src/reducer-builder.js~ReducerBuilder#scoped",
    "method"
  ],
  [
    "src/reducer-builder.js~reducerbuilder#select",
    "class/src/reducer-builder.js~ReducerBuilder.html#instance-method-select",
    "src/reducer-builder.js~ReducerBuilder#select",
    "method"
  ],
  [
    "src/reducer-builder.js~reducerbuilder#sum",
    "class/src/reducer-builder.js~ReducerBuilder.html#instance-method-sum",
    "src/reducer-builder.js~ReducerBuilder#sum",
    "method"
  ],
  [
    "src/reducer-builder.js~reducerbuilder#unwrap",
    "class/src/reducer-builder.js~ReducerBuilder.html#instance-method-unwrap",
    "src/reducer-builder.js~ReducerBuilder#unwrap",
    "method"
  ],
  [
    "src/reducer-builder.js~reducerbuilder#where",
    "class/src/reducer-builder.js~ReducerBuilder.html#instance-method-where",
    "src/reducer-builder.js~ReducerBuilder#where",
    "method"
  ],
  [
    "src/reducer-context.js",
    "file/src/reducer-context.js.html",
    "src/reducer-context.js",
    "file"
  ],
  [
    "src/reducer-context.js~reducercontext#constructor",
    "class/src/reducer-context.js~ReducerContext.html#instance-constructor-constructor",
    "src/reducer-context.js~ReducerContext#constructor",
    "method"
  ],
  [
    "src/reducer-context.js~reducercontext#getevent",
    "class/src/reducer-context.js~ReducerContext.html#instance-method-getEvent",
    "src/reducer-context.js~ReducerContext#getEvent",
    "method"
  ],
  [
    "src/reducer-context.js~reducercontext#getfreshvalue",
    "class/src/reducer-context.js~ReducerContext.html#instance-method-getFreshValue",
    "src/reducer-context.js~ReducerContext#getFreshValue",
    "method"
  ],
  [
    "src/reducer-context.js~reducercontext#getpreviousreduction",
    "class/src/reducer-context.js~ReducerContext.html#instance-method-getPreviousReduction",
    "src/reducer-context.js~ReducerContext#getPreviousReduction",
    "method"
  ],
  [
    "src/reducer-context.js~reducercontext#getstoredvalue",
    "class/src/reducer-context.js~ReducerContext.html#instance-method-getStoredValue",
    "src/reducer-context.js~ReducerContext#getStoredValue",
    "method"
  ],
  [
    "src/reducer-context.js~reducercontext#getvalue",
    "class/src/reducer-context.js~ReducerContext.html#instance-method-getValue",
    "src/reducer-context.js~ReducerContext#getValue",
    "method"
  ],
  [
    "src/reducer-context.js~reducercontext#nextauxillary",
    "class/src/reducer-context.js~ReducerContext.html#instance-member-nextAuxillary",
    "src/reducer-context.js~ReducerContext#nextAuxillary",
    "member"
  ],
  [
    "src/reducer-context.js~reducercontext#scopedby",
    "class/src/reducer-context.js~ReducerContext.html#instance-method-scopedBy",
    "src/reducer-context.js~ReducerContext#scopedBy",
    "method"
  ],
  [
    "src/reducer-context.js~reducercontext#storevalue",
    "class/src/reducer-context.js~ReducerContext.html#instance-method-storeValue",
    "src/reducer-context.js~ReducerContext#storeValue",
    "method"
  ],
  [
    "src/reducer-query.js",
    "file/src/reducer-query.js.html",
    "src/reducer-query.js",
    "file"
  ],
  [
    "src/reducer-query.js~reducerquery#reduce",
    "class/src/reducer-query.js~ReducerQuery.html#instance-method-reduce",
    "src/reducer-query.js~ReducerQuery#reduce",
    "method"
  ],
  [
    "src/reducer-query.js~reducerquery#tostore",
    "class/src/reducer-query.js~ReducerQuery.html#instance-method-toStore",
    "src/reducer-query.js~ReducerQuery#toStore",
    "method"
  ],
  [
    "src/reducer-query.js~reducerquery.newstate",
    "typedef/index.html#static-typedef-NewState",
    "src/reducer-query.js~ReducerQuery.NewState",
    "typedef"
  ],
  [
    "src/reducer-query.js~reducerquery.previousstate",
    "typedef/index.html#static-typedef-PreviousState",
    "src/reducer-query.js~ReducerQuery.PreviousState",
    "typedef"
  ],
  [
    "src/reducers/any-event-reducer.js",
    "file/src/reducers/any-event-reducer.js.html",
    "src/reducers/any-event-reducer.js",
    "file"
  ],
  [
    "src/reducers/collection-reducer.js",
    "file/src/reducers/collection-reducer.js.html",
    "src/reducers/collection-reducer.js",
    "file"
  ],
  [
    "src/reducers/collection-reducer.js~collectionreducer#constructor",
    "class/src/reducers/collection-reducer.js~CollectionReducer.html#instance-constructor-constructor",
    "src/reducers/collection-reducer.js~CollectionReducer#constructor",
    "method"
  ],
  [
    "src/reducers/dictionary-object-reducer.js",
    "file/src/reducers/dictionary-object-reducer.js.html",
    "src/reducers/dictionary-object-reducer.js",
    "file"
  ],
  [
    "src/reducers/dictionary-object-reducer.js~dictionaryobjectreducer#constructor",
    "class/src/reducers/dictionary-object-reducer.js~DictionaryObjectReducer.html#instance-constructor-constructor",
    "src/reducers/dictionary-object-reducer.js~DictionaryObjectReducer#constructor",
    "method"
  ],
  [
    "src/reducers/event-reducer.js",
    "file/src/reducers/event-reducer.js.html",
    "src/reducers/event-reducer.js",
    "file"
  ],
  [
    "src/reducers/event-reducer.js~eventreducer#constructor",
    "class/src/reducers/event-reducer.js~EventReducer.html#instance-constructor-constructor",
    "src/reducers/event-reducer.js~EventReducer#constructor",
    "method"
  ],
  [
    "src/reducers/filtered-reducer.js",
    "file/src/reducers/filtered-reducer.js.html",
    "src/reducers/filtered-reducer.js",
    "file"
  ],
  [
    "src/reducers/filtered-reducer.js~filteredreducer#constructor",
    "class/src/reducers/filtered-reducer.js~FilteredReducer.html#instance-constructor-constructor",
    "src/reducers/filtered-reducer.js~FilteredReducer#constructor",
    "method"
  ],
  [
    "src/reducers/flat-reduced-reducer.js",
    "file/src/reducers/flat-reduced-reducer.js.html",
    "src/reducers/flat-reduced-reducer.js",
    "file"
  ],
  [
    "src/reducers/flat-reduced-reducer.js~flatreducedreducer#constructor",
    "class/src/reducers/flat-reduced-reducer.js~FlatReducedReducer.html#instance-constructor-constructor",
    "src/reducers/flat-reduced-reducer.js~FlatReducedReducer#constructor",
    "method"
  ],
  [
    "src/reducers/folding-reducer.js",
    "file/src/reducers/folding-reducer.js.html",
    "src/reducers/folding-reducer.js",
    "file"
  ],
  [
    "src/reducers/folding-reducer.js~foldingreducer#constructor",
    "class/src/reducers/folding-reducer.js~FoldingReducer.html#instance-constructor-constructor",
    "src/reducers/folding-reducer.js~FoldingReducer#constructor",
    "method"
  ],
  [
    "src/reducers/linked-list-reducer.js",
    "file/src/reducers/linked-list-reducer.js.html",
    "src/reducers/linked-list-reducer.js",
    "file"
  ],
  [
    "src/reducers/linked-list-reducer.js~linkedlistreducer#constructor",
    "class/src/reducers/linked-list-reducer.js~LinkedListReducer.html#instance-constructor-constructor",
    "src/reducers/linked-list-reducer.js~LinkedListReducer#constructor",
    "method"
  ],
  [
    "src/reducers/mapped-reducer.js",
    "file/src/reducers/mapped-reducer.js.html",
    "src/reducers/mapped-reducer.js",
    "file"
  ],
  [
    "src/reducers/mapped-reducer.js~mappedreducer#constructor",
    "class/src/reducers/mapped-reducer.js~MappedReducer.html#instance-constructor-constructor",
    "src/reducers/mapped-reducer.js~MappedReducer#constructor",
    "method"
  ],
  [
    "src/reducers/never-reducer.js",
    "file/src/reducers/never-reducer.js.html",
    "src/reducers/never-reducer.js",
    "file"
  ],
  [
    "src/reducers/reducer.js",
    "file/src/reducers/reducer.js.html",
    "src/reducers/reducer.js",
    "file"
  ],
  [
    "src/reducers/reducer.js~reducer#reduce",
    "class/src/reducers/reducer.js~Reducer.html#instance-method-reduce",
    "src/reducers/reducer.js~Reducer#reduce",
    "method"
  ],
  [
    "src/reducers/scoped-reducer.js",
    "file/src/reducers/scoped-reducer.js.html",
    "src/reducers/scoped-reducer.js",
    "file"
  ],
  [
    "src/reducers/scoped-reducer.js~scopedreducer#constructor",
    "class/src/reducers/scoped-reducer.js~ScopedReducer.html#instance-constructor-constructor",
    "src/reducers/scoped-reducer.js~ScopedReducer#constructor",
    "method"
  ],
  [
    "src/reducers/storage-keys.js",
    "file/src/reducers/storage-keys.js.html",
    "src/reducers/storage-keys.js",
    "file"
  ],
  [
    "src/reducers/structure-reducer.js",
    "file/src/reducers/structure-reducer.js.html",
    "src/reducers/structure-reducer.js",
    "file"
  ],
  [
    "src/reducers/structure-reducer.js~structurereducer#constructor",
    "class/src/reducers/structure-reducer.js~StructureReducer.html#instance-constructor-constructor",
    "src/reducers/structure-reducer.js~StructureReducer#constructor",
    "method"
  ],
  [
    "src/reducers/value-reducer.js",
    "file/src/reducers/value-reducer.js.html",
    "src/reducers/value-reducer.js",
    "file"
  ],
  [
    "src/reducers/value-reducer.js~valuereducer#constructor",
    "class/src/reducers/value-reducer.js~ValueReducer.html#instance-constructor-constructor",
    "src/reducers/value-reducer.js~ValueReducer#constructor",
    "method"
  ]
]