export const TODO_ADDED = 'TODO_ADDED';
export const TODO_DELETED = 'TODO_DELETED';
export const TODO_EDITED = 'TODO_EDITED';
export const COMPLETION_CHANGED = 'COMPLETION_CHANGED';
export const COMPLETED_TODOS_CLEARED = 'COMPLETED_TODOS_CLEARED';
export const FILTER_CHANGED = 'FILTER_CHANGED';